server:
  port: 8081
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port:
      - 5672
      - 15672
    username: guest
    password: guest
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/compras
  mail:
    host: smtp.gmail.com
    port: 587
    username: gabrielffguimaraes@gmail.com
    password: vxxsuggvipmcdnvp
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls.enable: true
viacep: 'https://viacep.com.br/ws'